apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-nginx
  name: web-nginx
spec:
  containers:
  - image: nginx
    name: web-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
